# Generated by Django 4.1.5 on 2023-02-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_rename_name_useraccount_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
    ]
